### ISSUE TITLE
Dica para formatação markdown

### ISSUE THREAD

**Issue by alexandre-mbm** [OSMBrasil/Geolog-PMSP#2]
Use [grip](/joeyespo/grip) para previsualizar arquivos `.md` destinados a Github, assim:

``` console
$ grip --gfm --context=OSMBrasil/Geolog-PMSP
 * Running on http://localhost:5000/
```

**Comment by vgeorge** [comment]
Atom editor also has this feature. Open a `.md` file and press `ctrl-shift-m`:

https://atom.io/packages/markdown-preview

**Comment by alexandre-mbm** [comment]
I use Haroopad but these two do not have a GitHub style. Does Atom editor have?
