### ISSUE TITLE
Quadras 211 vs. quadras 212

### ISSUE THREAD

**Issue by alexandre-mbm** [OSMBrasil/Geolog-PMSP#4]
Qual é a distinção? Alguma diferença tem! Veja a comparação das duas primeiras _features_, abaixo:

``` diff
--- 211.geojson 2014-09-28 23:29:48.027657132 -0300
+++ 212.geojson 2014-09-28 23:29:56.343656613 -0300
@@ -3,8 +3,8 @@
 "crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },

 "features": [
-{ "type": "Feature", "properties": { "ID": 1, "QF": "12306800", "AREA": 8503.97 }, "geometry": { "type": "Polygon", "coordinates": [ [ [ -46.731839259368236, -23.601596395910441 ], [ -46.73171825848835, -23.601510396054731 ], [ -46.731614257778688, -23.601452396207726 ], [ -46.731502257018718, -23.601391396375153 ], [ -46.73142025652281, -23.601367396535338 ], [ -46.731322255908701, -23.601331396713473 ], [ -46.731229255376185, -23.601314396913754 ], [ -46.731139254829962, -23.60128739708837 ], [ -46.731031254204929, -23.601265397316848 ], [ -46.73088725340768, -23.601248397643939 ], [ -46.730756252721825, -23.601246397966015 ], [ -46.730690252376277, -23.601245398128292 ], [ -46.730563251755086, -23.601258398467753 ], [ -46.730449251233601, -23.601282398794904 ], [ -46.73036525087074, -23.601307399049286 ], [ -46.730296250585759, -23.601332399266358 ], [ -46.730281250654279, -23.601382399394701 ], [ -46.730339251198345, -23.601465399401633 ], [ -46.730468252315909, -23.601618399359495 ], [ -46.731678260002298, -23.60209839722479 ], [ -46.731839259368236, -23.601596395910441 ] ] ] } },
-{ "type": "Feature", "properties": { "ID": 2, "QF": "12306600", "AREA": 8465.38 }, "geometry": { "type": "Polygon", "coordinates": [ [ [ -46.73050125709856, -23.603193402145251 ], [ -46.729908253499005, -23.603015403295675 ], [ -46.729178248895479, -23.602737404604603 ], [ -46.729286251271375, -23.603357405465026 ], [ -46.730323258080645, -23.603844403773206 ], [ -46.73050125709856, -23.603193402145251 ] ] ] } },
+{ "type": "Feature", "properties": { "ID": 1, "Area": 8523.827148, "QF": null }, "geometry": { "type": "Polygon", "coordinates": [ [ [ -46.731839259368236, -23.601596395910441 ], [ -46.73171825848835, -23.601510396054731 ], [ -46.731614257778688, -23.601452396207726 ], [ -46.731502257018718, -23.601391396375153 ], [ -46.73142025652281, -23.601367396535338 ], [ -46.731322255908701, -23.601331396713473 ], [ -46.731229255376185, -23.601314396913754 ], [ -46.731139254829962, -23.60128739708837 ], [ -46.731031254204929, -23.601265397316848 ], [ -46.73088725340768, -23.601248397643939 ], [ -46.730756252721825, -23.601246397966015 ], [ -46.730690252376277, -23.601245398128292 ], [ -46.730563251755086, -23.601258398467753 ], [ -46.730449251233601, -23.601282398794904 ], [ -46.73036525087074, -23.601307399049286 ], [ -46.730296250585759, -23.601332399266358 ], [ -46.730281250654279, -23.601382399394701 ], [ -46.730339251198345, -23.601465399401633 ], [ -46.730468252315909, -23.601618399359495 ], [ -46.731678260002298, -23.60209839722479 ], [ -46.731839259368236, -23.601596395910441 ] ] ] } },
+{ "type": "Feature", "properties": { "ID": 2, "Area": 8485.526367, "QF": null }, "geometry": { "type": "Polygon", "coordinates": [ [ [ -46.73050125709856, -23.603193402145251 ], [ -46.729908253499005, -23.603015403295675 ], [ -46.729178248895479, -23.602737404604603 ], [ -46.729286251271375, -23.603357405465026 ], [ -46.730323258080645, -23.603844403773206 ], [ -46.73050125709856, -23.603193402145251 ] ] ] } },
```

O código da quadra fiscal é nulo no arquivo 212. Será ele inválido? Notem que o nome até tem um caractere de espaço. Na dúvida, vou usando apenas o 211. Talvez as geometrias sejam mesmo todas exatamente iguais, sendo ele a versão final.

**Comment by vgeorge** [comment]
Não cheguei a olhar as quadras. Não vejo necessidade de importar, já que é uma denominação interna da prefeitura para fins fiscais.

**Comment by alexandre-mbm** [comment]
Meu interesse nelas e nos setores não é para importação. Seriam usados no algoritmo de criação de polígonos para o Tasking Manager, como explicado em [comentário da issue #3](../issues/3#issuecomment-57106709). Aqueles polígonos poderiam ajudar muito a organizar o trabalho, pois eles fariam **tarefas Tasking Manager de tamanho configurável e contendo somente logradouros completos**.

O único problema é que vou viajar de carona agora a tarde e não tenho mais tempo de prosseguir. Vou ser o caseiro e cuidar, por talvez 15 dias, de minha avó de 87 anos com Alzheimer e meu tio de 44 anos com síndrome de Down. Meu pai precisa investigar a própria saúde em outra cidade, durante esse tempo. Peço que não se prendam ao que comecei mas, por outro lado, não apaguem o diretório tasking-manager até eu chegar. As coisas parecem muito iniciais no código (que hoje é só um trabalho em exemplos muito breves) mas eu pesquisei e pensei bastante.

Meu interesse nessas coisas, se eu não mapeio São Paulo, é "treinar" para implementar importação de Mapillary em Tasking Manager, [uma issue pessoal](alexandre-mbm/osm-tasking-manager2#4).

**Comment by alexandre-mbm** [comment]
Estou fechando esta issue apenas porque o arquivo 212 parece ser lixo (mal duplicado). 

Se o que tenho feito e quero que fique guardado é básico demais para alguns de vocês que já estavam ambientados com ogr2ogr, desculpem-me. Eu tenho praticado essas coisas somente agora.

**Comment by alexandre-mbm** [comment]
Invés de 15 dias, foram apenas 7. Cheguei ontem. Continuarei o que comecei, mas num ritmo lento. Meus pais chegaram. Minha avó e meu tio estão conosco. A pessoa que trabalha aqui está de férias, etc. Comento aqui aproveitando o comentário que fechou esta _issue_.
